# Site settings
title: Pizza Shelf
email: ""
description: "Real Neapolitan Pizza in Your Own Oven"
url: "http://rotiofood.com"
baseurl: /thepizzashelf
instagram_username: "anthony.rotio"
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   "Pizza Shelf"
  avatar: avatar.png
  favicon: 
  description: "Photo Journal"

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Mailchimp sign up
mailchimp: true
mailchimp_list_name: Friends and Family List
mailchimp_list_why: Be the first to know when we launch so you can make Neapolitan pizza in your own oven ASAP!
mailchimp_embed_action: http://thepizzashelf.us14.list-manage.com/subscribe/post?u=2f593f12350851aa6aae1f1bb&amp;id=de7d633d72

# Internal nav
nav:
 journal: "baseurl/journal/"
 gallery: "baseurl/gallery/"
 about: "baseurl/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"